---

- hosts: all
  become: true
  tasks:

# Linx Mint
  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Linux Mint"

  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Linux Mint"

  - name: Add php support for Apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Linux Mint"

  - name: Add Htop
    apt:
      name: htop
      state: latest
    when: ansible_distribution == "Linux Mint"

# Oracle Linux

  - name: Update Repository Index
    dnf:
      update_cache: yes
    when: ansible_distribution == "OracleLinux" 

  - name: Install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: Add php support to apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "OracleLinux"

