---

- hosts: all
  become: true
  tasks:

  - name: Update Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution == "Linux Mint" and ansible_architecture == "x86_64"


  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Linux Mint" and ansible_architecture == "x86_64"


  - name: Add php support for Apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Linux Mint" and ansible_architecture == "x86_64"


  - name: Add Htop
    apt:
      name: htop
      state: latest
    when: ansible_distribution == "Linux Mint" and ansible_architecture == "x86_64"

